/* Generated by cbindgen — do not edit */

#ifndef BEE_FFI_H
#define BEE_FFI_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct AsrEngine AsrEngine;

typedef struct AsrSession AsrSession;

/**
 * Opaque correction engine handle.
 */
typedef struct CorrectionEngine CorrectionEngine;

/**
 * Opaque correction result handle.
 */
typedef struct CorrectionResult CorrectionResult;

typedef struct AsrModelPaths {
  /**
   * Base cache directory containing all model subdirectories.
   */
  const char *cache_dir;
} AsrModelPaths;

typedef struct AsrEngineStats {
  float cpu_percent;
  float gpu_percent;
  float vram_used_mb;
  float ram_used_mb;
} AsrEngineStats;

typedef struct AsrSessionOptions {
  float chunk_size_sec;
  float session_duration_sec;
  const char *language;
  const char *prompt;
  unsigned int unfixed_chunk_num;
  unsigned int unfixed_token_num;
  unsigned int rollback_token_num;
  unsigned int max_new_tokens_streaming;
  unsigned int max_new_tokens_final;
} AsrSessionOptions;

typedef struct AsrFeedResult {
  char *text;
  uintptr_t committed_utf16_len;
  char *alignments_json;
  char *debug_json;
} AsrFeedResult;

void bee_ffi_bootstrap(void);

/**
 * Set the path for FFI diagnostic logs. Call this before loading any engine.
 * Pass NULL to disable file logging.
 */
void asr_set_log_path(const char *path);

/**
 * # Safety
 * `model_dir` and `paths.cache_dir` must be valid, nul-terminated UTF-8 pointers.
 */
struct AsrEngine *asr_engine_load(const char *model_dir,
                                  struct AsrModelPaths paths,
                                  char **out_err);

/**
 * # Safety
 * `model_id` and `paths.cache_dir` must be valid, nul-terminated UTF-8 pointers.
 */
struct AsrEngine *asr_engine_from_pretrained(const char *model_id,
                                             struct AsrModelPaths paths,
                                             char **out_err);

struct AsrEngine *asr_engine_from_gguf(const char *_base_repo_id,
                                       const char *_gguf_repo_id,
                                       const char *_gguf_filename,
                                       struct AsrModelPaths _paths,
                                       char **out_err);

char *asr_engine_transcribe_samples(const struct AsrEngine *_engine,
                                    const float *_samples,
                                    uintptr_t _num_samples,
                                    char **out_err);

/**
 * # Safety
 * `engine` must be a pointer returned by this module and not yet freed.
 */
void asr_engine_free(struct AsrEngine *engine);

/**
 * # Safety
 * `engine` must be a valid engine pointer.
 */
struct AsrEngineStats asr_engine_get_stats(const struct AsrEngine *engine);

/**
 * # Safety
 * `engine` must be a valid engine pointer.
 */
struct AsrSession *asr_session_create(const struct AsrEngine *engine,
                                      struct AsrSessionOptions opts);

struct AsrFeedResult asr_session_feed(struct AsrSession *session,
                                      const float *samples,
                                      uintptr_t num_samples,
                                      char **out_err);

struct AsrFeedResult asr_session_feed_finalizing(struct AsrSession *session,
                                                 const float *samples,
                                                 uintptr_t num_samples,
                                                 char **out_err);

void asr_feed_result_free(struct AsrFeedResult result);

/**
 * # Safety
 * `session` must be a valid session pointer.
 */
char *asr_session_finish(struct AsrSession *session, char **out_err);

/**
 * # Safety
 * `session` must be a valid session pointer.
 */
char *asr_session_last_language(const struct AsrSession *_session);

bool asr_session_set_language(struct AsrSession *_session, const char *_language, char **_out_err);

/**
 * # Safety
 * `session` must be a valid session pointer.
 */
void asr_session_free(struct AsrSession *session);

/**
 * # Safety
 * `s` must be either null or a pointer returned by this module.
 */
void asr_string_free(char *s);

/**
 * Load a correction engine. Returns NULL on error.
 *
 * # Safety
 * All string pointers must be valid nul-terminated UTF-8 or NULL.
 */
struct CorrectionEngine *bee_correct_engine_load(const char *dataset_dir,
                                                 const char *events_path,
                                                 float gate_threshold,
                                                 float ranker_threshold,
                                                 char **out_err);

/**
 * Process a transcript and return correction results.
 *
 * `transcript_json` is a JSON object: `{ "text": "...", "app_id": "..." }`
 *
 * # Safety
 * `engine` must be a valid pointer. `transcript_json` must be valid UTF-8.
 */
struct CorrectionResult *bee_correct_process(struct CorrectionEngine *engine,
                                             const char *transcript_json,
                                             char **out_err);

/**
 * Get the session ID from a correction result.
 */
char *bee_correction_result_session_id(const struct CorrectionResult *result);

/**
 * Get the corrected text.
 */
char *bee_correction_result_best_text(const struct CorrectionResult *result);

/**
 * Get the edits as JSON.
 */
const char *bee_correction_result_json(const struct CorrectionResult *result);

/**
 * Get the number of edits.
 */
uint32_t bee_correction_result_edit_count(const struct CorrectionResult *result);

/**
 * Free a correction result.
 */
void bee_correction_result_free(struct CorrectionResult *result);

/**
 * Teach the judge from user feedback.
 *
 * `teach_json`: `{ "edits": [{"edit_id": "e0", "resolution": "accepted"}], ... }`
 *
 * # Safety
 * `engine` must be valid. `session_id` and `teach_json` must be valid UTF-8.
 */
void bee_correct_teach(struct CorrectionEngine *engine,
                       const char *_session_id,
                       const char *_teach_json,
                       char **_out_err);

/**
 * Save judge weights and flush events.
 *
 * # Safety
 * `engine` must be a valid pointer.
 */
void bee_correct_save(struct CorrectionEngine *_engine, char **_out_err);

/**
 * Free a correction engine.
 */
void bee_correct_engine_free(struct CorrectionEngine *engine);

#endif  /* BEE_FFI_H */
