/* eslint-disable */
// Generated by `cargo run -p beeml --bin gen-ts-api`

// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --typescript`

import type { Caller, MethodDescriptor, ServiceDescriptor, VoxCall, Dispatcher, RequestContext, SessionTransportOptions } from "@bearcove/vox-core";
import { session } from "@bearcove/vox-core";
import { wsConnector } from "@bearcove/vox-ws";
import { RpcError } from "@bearcove/vox-core";

// Named type definitions
export interface ForcedAlignItem {
  word: string;
  start_time: number;
  end_time: number;
}

export interface TranscribeWavResult {
  transcript: string;
  qwen_words: ForcedAlignItem[];
}

// Request/Response type aliases
export type TranscribeWavRequest = [Uint8Array];
export type TranscribeWavResponse = { ok: true; value: TranscribeWavResult } | { ok: false; error: string };

// Caller interface for BeeMl
export interface BeeMlCaller {
  transcribeWav(wavBytes: Uint8Array): Promise<{ ok: true; value: TranscribeWavResult } | { ok: false; error: string }>;
}

// Client implementation for BeeMl
export class BeeMlClient implements BeeMlCaller {
  private caller: Caller;

  constructor(caller: Caller) {
    this.caller = caller;
  }

  async transcribeWav(wavBytes: Uint8Array): Promise<{ ok: true; value: TranscribeWavResult } | { ok: false; error: string }> {
    const descriptor = beeMl_transcribeWav_method;
    const sendSchemas = beeMl_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "BeeMl.transcribeWav",
          args: { wavBytes },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: TranscribeWavResult } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: TranscribeWavResult } | { ok: false; error: string };
        }
        throw e;
      }
  }

}

/**
 * Connect to a BeeMl server over WebSocket.
 * @param url - WebSocket URL (e.g., "ws://localhost:9000")
 * @returns A connected BeeMlClient instance
 */
export async function connectBeeMl(
  url: string,
  options: SessionTransportOptions = {},
): Promise<BeeMlClient> {
  const established = await session.initiator(wsConnector(url), options);
  return new BeeMlClient(established.rootConnection().caller());
}

// Handler interface for BeeMl
export interface BeeMlHandler {
  transcribeWav(wavBytes: Uint8Array): Promise<{ ok: true; value: TranscribeWavResult } | { ok: false; error: string }> | { ok: true; value: TranscribeWavResult } | { ok: false; error: string };
}

// Dispatcher for BeeMl
export class BeeMlDispatcher implements Dispatcher {
  private readonly handler: BeeMlHandler;

  constructor(handler: BeeMlHandler) {
    this.handler = handler;
  }

  getDescriptor(): ServiceDescriptor {
    return beeMl_descriptor;
  }

  async dispatch(_context: RequestContext, method: MethodDescriptor, args: unknown[], call: VoxCall): Promise<void> {
    if (method.id === 0x5769301e350ea60bn) {
      try {
        const result = await this.handler.transcribeWav(args[0] as Uint8Array);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    }
  }
}

// Schema objects for wire schema exchange (TypeScript → Rust)
// Generated from Rust Facet shapes — do not modify.
export const beeMl_send_schemas: import("@bearcove/vox-core").ServiceSendSchemas = {
  schemas: new Map<bigint, import("@bearcove/vox-postcard").Schema>([
    [0x178367a87f66fb46n, { id: 0x178367a87f66fb46n, type_params: [], kind: { tag: 'primitive', primitive_type: 'bool' } }],
    [0x281c5be4f2ee63b4n, { id: 0x281c5be4f2ee63b4n, type_params: [], kind: { tag: 'primitive', primitive_type: 'u32' } }],
    [0x42046de663beeef0n, { id: 0x42046de663beeef0n, type_params: ['T', 'E'], kind: { tag: 'enum', name: 'Result', variants: [{ name: 'Ok', index: 0, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'T' } } }, { name: 'Err', index: 1, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'E' } } }] } }],
    [0x5db70a394660f3e6n, { id: 0x5db70a394660f3e6n, type_params: [], kind: { tag: 'primitive', primitive_type: 'never' } }],
    [0x6d7dce914ee150e8n, { id: 0x6d7dce914ee150e8n, type_params: [], kind: { tag: 'primitive', primitive_type: 'string' } }],
    [0x4cf4b2aeb98a1939n, { id: 0x4cf4b2aeb98a1939n, type_params: ['E'], kind: { tag: 'enum', name: 'VoxError', variants: [{ name: 'User', index: 0, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'E' } } }, { name: 'UnknownMethod', index: 1, payload: { tag: 'unit' } }, { name: 'InvalidPayload', index: 2, payload: { tag: 'newtype', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] } } }, { name: 'Cancelled', index: 3, payload: { tag: 'unit' } }, { name: 'ConnectionClosed', index: 4, payload: { tag: 'unit' } }, { name: 'SessionShutdown', index: 5, payload: { tag: 'unit' } }, { name: 'SendFailed', index: 6, payload: { tag: 'unit' } }, { name: 'Indeterminate', index: 7, payload: { tag: 'unit' } }] } }],
    [0xba8125876d6388b4n, { id: 0xba8125876d6388b4n, type_params: [], kind: { tag: 'primitive', primitive_type: 'bytes' } }],
    [0x6847ab90feda71c1n, { id: 0x6847ab90feda71c1n, type_params: ['T0'], kind: { tag: 'tuple', elements: [{ tag: 'var', name: 'T0' }] } }],
    [0x3f2e589db81e95bfn, { id: 0x3f2e589db81e95bfn, type_params: [], kind: { tag: 'primitive', primitive_type: 'f64' } }],
    [0xd3d5370bbeaf7b98n, { id: 0xd3d5370bbeaf7b98n, type_params: [], kind: { tag: 'struct', name: 'ForcedAlignItem', fields: [{ name: 'word', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'start_time', type_ref: { tag: 'concrete', type_id: 0x3f2e589db81e95bfn, args: [] }, required: true }, { name: 'end_time', type_ref: { tag: 'concrete', type_id: 0x3f2e589db81e95bfn, args: [] }, required: true }] } }],
    [0x0a96b404b4d79d67n, { id: 0x0a96b404b4d79d67n, type_params: ['T'], kind: { tag: 'list', element: { tag: 'var', name: 'T' } } }],
    [0xf4459a1e5148779cn, { id: 0xf4459a1e5148779cn, type_params: [], kind: { tag: 'struct', name: 'TranscribeWavResult', fields: [{ name: 'transcript', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'qwen_words', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xd3d5370bbeaf7b98n, args: [] }] }, required: true }] } }],
  ]),
  methods: new Map<bigint, import("@bearcove/vox-core").MethodSendSchemas>([
    [0x5769301e350ea60bn, { argsRootRef: { tag: 'concrete', type_id: 0x6847ab90feda71c1n, args: [{ tag: 'concrete', type_id: 0xba8125876d6388b4n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0xf4459a1e5148779cn, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
  ]),
};

export const beeMl_transcribeWav_method: MethodDescriptor = {
  name: 'transcribeWav',
  id: 0x5769301e350ea60bn,
  retry: { persist: false, idem: false },
};

// Service descriptor for runtime dispatch metadata
export const beeMl_descriptor: ServiceDescriptor = {
  service_name: 'BeeMl',
  send_schemas: beeMl_send_schemas,
  methods: new Map<bigint, MethodDescriptor>([
    [beeMl_transcribeWav_method.id, beeMl_transcribeWav_method],
  ]),
};

