// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import Foundation
import VoxRuntime

// MARK: - App Method IDs

public enum AppMethodId {
    public static let imeHello: UInt64 = 0x75699685b1a93d32
    public static let claimSession: UInt64 = 0xa450881492adee30
    public static let imeAttach: UInt64 = 0x8a60f92280588cd0
    public static let imeActivationRevoked: UInt64 = 0x069f4682025f282c
    public static let imeContextLost: UInt64 = 0xf05b46d1538b1ac3
    public static let imeKeyEvent: UInt64 = 0x70404de7bbc58de7
}

// MARK: - App Types

// MARK: - App Client

///  Methods the app exposes — IME calls into app.
public protocol AppCaller {
    ///  IME says hello, returns app instance ID.
    func imeHello() async throws -> String
    ///  IME claims the prepared session. Returns session ID if one
    ///  was waiting, or empty string if none.
    func claimSession() async throws -> String
    ///  IME attached to the session (activateServer confirmed).
    func imeAttach(sessionId: String) async throws -> Bool
    ///  IME notifies app that activation was revoked (spurious deactivate).
    func imeActivationRevoked() async throws -> Bool
    ///  IME notifies app that it lost context (deactivateServer with no session).
    func imeContextLost(hadMarkedText: Bool) async throws -> Bool
    ///  IME notifies app of a key event (submit, cancel, user typed).
    func imeKeyEvent(sessionId: String, eventType: String, keyCode: UInt32, characters: String) async throws -> Bool
}

public final class AppClient: AppCaller, Sendable {
    private let connection: VoxConnection
    private let timeout: TimeInterval?

    public init(connection: VoxConnection, timeout: TimeInterval? = 30.0) {
        self.connection = connection
        self.timeout = timeout
    }

    public func imeHello() async throws -> String {
        let payload = Data()
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0x75699685b1a93d32]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0x75699685b1a93d32, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeString(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func claimSession() async throws -> String {
        let payload = Data()
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0xa450881492adee30]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0xa450881492adee30, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeString(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func imeAttach(sessionId: String) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0x8a60f92280588cd0]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0x8a60f92280588cd0, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func imeActivationRevoked() async throws -> Bool {
        let payload = Data()
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0x069f4682025f282c]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0x069f4682025f282c, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func imeContextLost(hadMarkedText: Bool) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeBool(hadMarkedText)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0xf05b46d1538b1ac3]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0xf05b46d1538b1ac3, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func imeKeyEvent(sessionId: String, eventType: String, keyCode: UInt32, characters: String) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        payloadBytes += encodeString(eventType)
        payloadBytes += encodeU32(keyCode)
        payloadBytes += encodeString(characters)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: app_method_schemas[0x70404de7bbc58de7]!, schemaRegistry: app_schema_registry)
        let response = try await connection.call(methodId: 0x70404de7bbc58de7, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }
}

// MARK: - App Server

///  Methods the app exposes — IME calls into app.
public protocol AppHandler: Sendable {
    ///  IME says hello, returns app instance ID.
    func imeHello() async throws -> String
    ///  IME claims the prepared session. Returns session ID if one
    ///  was waiting, or empty string if none.
    func claimSession() async throws -> String
    ///  IME attached to the session (activateServer confirmed).
    func imeAttach(sessionId: String) async throws -> Bool
    ///  IME notifies app that activation was revoked (spurious deactivate).
    func imeActivationRevoked() async throws -> Bool
    ///  IME notifies app that it lost context (deactivateServer with no session).
    func imeContextLost(hadMarkedText: Bool) async throws -> Bool
    ///  IME notifies app of a key event (submit, cancel, user typed).
    func imeKeyEvent(sessionId: String, eventType: String, keyCode: UInt32, characters: String) async throws -> Bool
}

public final class AppChannelingDispatcher: ServiceDispatcher {
    private let handler: AppHandler
    private let schemaRegistry: [UInt64: Schema]
    private let methodSchemas: [UInt64: MethodSchemaInfo]

    public init(handler: AppHandler, schemaRegistry: [UInt64: Schema] = app_schema_registry, methodSchemas: [UInt64: MethodSchemaInfo] = app_method_schemas) {
        self.handler = handler
        self.schemaRegistry = schemaRegistry
        self.methodSchemas = methodSchemas
    }

    public func dispatch(methodId: UInt64, payload: [UInt8], requestId: UInt64, registry: ChannelRegistry, schemaSendTracker _: SchemaSendTracker, taskTx: @escaping @Sendable (TaskMessage) -> Void) async {
        let payload = Data(payload)
        let taskSender: TaskSender = taskTx
        switch methodId {
        case 0x75699685b1a93d32:
            await dispatch_imeHello(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0xa450881492adee30:
            await dispatch_claimSession(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x8a60f92280588cd0:
            await dispatch_imeAttach(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x069f4682025f282c:
            await dispatch_imeActivationRevoked(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0xf05b46d1538b1ac3:
            await dispatch_imeContextLost(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x70404de7bbc58de7:
            await dispatch_imeKeyEvent(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        default:
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
        }
    }

    public func retryPolicy(methodId: UInt64) -> RetryPolicy {
        switch methodId {
        case 0x75699685b1a93d32:
            return .volatile
        case 0xa450881492adee30:
            return .volatile
        case 0x8a60f92280588cd0:
            return .volatile
        case 0x069f4682025f282c:
            return .volatile
        case 0xf05b46d1538b1ac3:
            return .volatile
        case 0x70404de7bbc58de7:
            return .volatile
        default:
            return .volatile
        }
    }

    /// Pre-register Rx channel IDs from request payloads.
    /// Call this synchronously before spawning the dispatch task to avoid
    /// race conditions where Data arrives before channels are registered.
    public func preregister(methodId: UInt64, payload: [UInt8], registry: ChannelRegistry) async {
        let payload = Data(payload)
        switch methodId {
        default:
            break
        }
    }

    private func dispatch_imeHello(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.imeHello()
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeString($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_claimSession(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.claimSession()
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeString($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_imeAttach(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            do {
                let result = try await handler.imeAttach(sessionId: sessionId)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_imeActivationRevoked(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.imeActivationRevoked()
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_imeContextLost(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let hadMarkedText = try decodeBool(from: payload, offset: &cursor)
            do {
                let result = try await handler.imeContextLost(hadMarkedText: hadMarkedText)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_imeKeyEvent(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            let eventType = try decodeString(from: payload, offset: &cursor)
            let keyCode = try decodeU32(from: payload, offset: &cursor)
            let characters = try decodeString(from: payload, offset: &cursor)
            do {
                let result = try await handler.imeKeyEvent(sessionId: sessionId, eventType: eventType, keyCode: keyCode, characters: characters)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

}

// MARK: - App Schemas

public let app_schemas: [String: MethodBindingSchema] = [
    "imeHello": MethodBindingSchema(args: []),
    "claimSession": MethodBindingSchema(args: []),
    "imeAttach": MethodBindingSchema(args: [.string]),
    "imeActivationRevoked": MethodBindingSchema(args: []),
    "imeContextLost": MethodBindingSchema(args: [.bool]),
    "imeKeyEvent": MethodBindingSchema(args: [.string, .string, .u32, .string]),
]

/// Global schema registry containing all schemas for this service.
nonisolated(unsafe) public let app_schema_registry: [UInt64: Schema] = [
    0x178367a87f66fb46: Schema(id: 0x178367a87f66fb46, typeParams: [], kind: .primitive(.bool)),
    0x281c5be4f2ee63b4: Schema(id: 0x281c5be4f2ee63b4, typeParams: [], kind: .primitive(.u32)),
    0x42046de663beeef0: Schema(id: 0x42046de663beeef0, typeParams: ["T", "E"], kind: .enum(name: "Result", variants: [VariantSchema(name: "Ok", index: 0, payload: .newtype(typeRef: .var(name: "T"))), VariantSchema(name: "Err", index: 1, payload: .newtype(typeRef: .var(name: "E")))])),
    0x4cf4b2aeb98a1939: Schema(id: 0x4cf4b2aeb98a1939, typeParams: ["E"], kind: .enum(name: "VoxError", variants: [VariantSchema(name: "User", index: 0, payload: .newtype(typeRef: .var(name: "E"))), VariantSchema(name: "UnknownMethod", index: 1, payload: .unit), VariantSchema(name: "InvalidPayload", index: 2, payload: .newtype(typeRef: .concrete(0x6d7dce914ee150e8))), VariantSchema(name: "Cancelled", index: 3, payload: .unit), VariantSchema(name: "ConnectionClosed", index: 4, payload: .unit), VariantSchema(name: "SessionShutdown", index: 5, payload: .unit), VariantSchema(name: "SendFailed", index: 6, payload: .unit), VariantSchema(name: "Indeterminate", index: 7, payload: .unit)])),
    0x5db70a394660f3e6: Schema(id: 0x5db70a394660f3e6, typeParams: [], kind: .primitive(.never)),
    0x6847ab90feda71c1: Schema(id: 0x6847ab90feda71c1, typeParams: ["T0"], kind: .tuple(elements: [.var(name: "T0")])),
    0x6d7dce914ee150e8: Schema(id: 0x6d7dce914ee150e8, typeParams: [], kind: .primitive(.string)),
    0x915c6fb5b64f270b: Schema(id: 0x915c6fb5b64f270b, typeParams: ["T0", "T1", "T2", "T3"], kind: .tuple(elements: [.var(name: "T0"), .var(name: "T1"), .var(name: "T2"), .var(name: "T3")])),
    0xbc5c33249a2dc720: Schema(id: 0xbc5c33249a2dc720, typeParams: [], kind: .primitive(.unit)),
]

/// Per-method schema information for wire protocol.
nonisolated(unsafe) public let app_method_schemas: [UInt64: MethodSchemaInfo] = [
    0x75699685b1a93d32: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6d7dce914ee150e8), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0xa450881492adee30: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6d7dce914ee150e8), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x8a60f92280588cd0: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x069f4682025f282c: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0xf05b46d1538b1ac3: MethodSchemaInfo(
        argsSchemaIds: [0x178367a87f66fb46, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x178367a87f66fb46)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x70404de7bbc58de7: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x281c5be4f2ee63b4, 0x915c6fb5b64f270b],
        argsRoot: .generic(0x915c6fb5b64f270b, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8), .concrete(0x281c5be4f2ee63b4), .concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
]

public struct AppSerializers: BindingSerializers {
    public init() {}

    public func txSerializer(for schema: BindingSchema) -> @Sendable (Any) -> [UInt8] {
        switch schema {
        case .bool: return { encodeBool($0 as! Bool) }
        case .u8: return { encodeU8($0 as! UInt8) }
        case .i8: return { encodeI8($0 as! Int8) }
        case .u16: return { encodeU16($0 as! UInt16) }
        case .i16: return { encodeI16($0 as! Int16) }
        case .u32: return { encodeU32($0 as! UInt32) }
        case .i32: return { encodeI32($0 as! Int32) }
        case .u64: return { encodeVarint($0 as! UInt64) }
        case .i64: return { encodeI64($0 as! Int64) }
        case .f32: return { encodeF32($0 as! Float) }
        case .f64: return { encodeF64($0 as! Double) }
        case .string: return { encodeString($0 as! String) }
        case .bytes: return { [UInt8]($0 as! Data) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not serialized directly")
        default: fatalError("Unsupported schema for Tx serialization: \(schema)")
        }
    }

    public func rxDeserializer(for schema: BindingSchema) -> @Sendable ([UInt8]) throws -> Any {
        switch schema {
        case .bool: return { var o = 0; return try decodeBool(from: Data($0), offset: &o) }
        case .u8: return { var o = 0; return try decodeU8(from: Data($0), offset: &o) }
        case .i8: return { var o = 0; return try decodeI8(from: Data($0), offset: &o) }
        case .u16: return { var o = 0; return try decodeU16(from: Data($0), offset: &o) }
        case .i16: return { var o = 0; return try decodeI16(from: Data($0), offset: &o) }
        case .u32: return { var o = 0; return try decodeU32(from: Data($0), offset: &o) }
        case .i32: return { var o = 0; return try decodeI32(from: Data($0), offset: &o) }
        case .u64: return { var o = 0; return try decodeVarint(from: Data($0), offset: &o) }
        case .i64: return { var o = 0; return try decodeI64(from: Data($0), offset: &o) }
        case .f32: return { var o = 0; return try decodeF32(from: Data($0), offset: &o) }
        case .f64: return { var o = 0; return try decodeF64(from: Data($0), offset: &o) }
        case .string: return { var o = 0; return try decodeString(from: Data($0), offset: &o) }
        case .bytes: return { Data($0) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not deserialized directly")
        default: fatalError("Unsupported schema for Rx deserialization: \(schema)")
        }
    }
}

