// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import Foundation
@preconcurrency import NIOCore
import VoxRuntime

// MARK: - Bee Method IDs

public enum BeeMethodId {
    public static let requiredDownloads: UInt64 = 0xec7becd2deb1dad4
    public static let loadEngine: UInt64 = 0x1c123a5c2762d6a5
    public static let createSession: UInt64 = 0xed77a6d793863a25
    public static let feed: UInt64 = 0xc7e28a8816c1bc83
    public static let finishSession: UInt64 = 0x416a48f228b25310
    public static let setLanguage: UInt64 = 0xefb09d27037e41ed
    public static let transcribeSamples: UInt64 = 0xbb649049c66f9f90
    public static let getStats: UInt64 = 0xac27f8b9cda1c89f
    public static let correctLoad: UInt64 = 0xc6ef90e080c66309
    public static let correctProcess: UInt64 = 0xd383d61a2c875e84
    public static let correctTeach: UInt64 = 0x2163f1014480c2db
    public static let correctSave: UInt64 = 0xa5b4730fb9dbaa99
}

// MARK: - Bee Types

public struct RepoFile: Codable, Sendable {
    public var name: String
    public var url: String

    nonisolated public init(name: String, url: String) {
        self.name = name
        self.url = url
    }
}

public struct RepoDownload: Codable, Sendable {
    public var repoId: String
    public var localDir: String
    public var files: [RepoFile]

    nonisolated public init(repoId: String, localDir: String, files: [RepoFile]) {
        self.repoId = repoId
        self.localDir = localDir
        self.files = files
    }
}

public enum BeeError: Codable, Sendable, Error {
    case engineNotLoaded
    case sessionNotFound(sessionId: String)
    case loadFailed(message: String)
    case transcriptionError(message: String)
    case correctionError(message: String)
    case notImplemented
}

public struct SessionConfig: Codable, Sendable {
    public var language: String
    public var chunkDuration: Float
    public var vadThreshold: Float
    public var rollbackTokens: UInt32
    public var commitTokenCount: UInt32

    nonisolated public init(language: String, chunkDuration: Float, vadThreshold: Float, rollbackTokens: UInt32, commitTokenCount: UInt32) {
        self.language = language
        self.chunkDuration = chunkDuration
        self.vadThreshold = vadThreshold
        self.rollbackTokens = rollbackTokens
        self.commitTokenCount = commitTokenCount
    }
}

public struct AlignedWord: Codable, Sendable {
    public var word: String
    public var start: Double
    public var end: Double
    public var meanLogprob: Float?
    public var minLogprob: Float?
    public var meanMargin: Float?
    public var minMargin: Float?

    nonisolated public init(word: String, start: Double, end: Double, meanLogprob: Float?, minLogprob: Float?, meanMargin: Float?, minMargin: Float?) {
        self.word = word
        self.start = start
        self.end = end
        self.meanLogprob = meanLogprob
        self.minLogprob = minLogprob
        self.meanMargin = meanMargin
        self.minMargin = minMargin
    }
}

public struct FeedResult: Codable, Sendable {
    public var text: String
    public var committedUtf16Len: UInt32
    public var alignments: [AlignedWord]
    public var isFinal: Bool
    public var detectedLanguage: String

    nonisolated public init(text: String, committedUtf16Len: UInt32, alignments: [AlignedWord], isFinal: Bool, detectedLanguage: String) {
        self.text = text
        self.committedUtf16Len = committedUtf16Len
        self.alignments = alignments
        self.isFinal = isFinal
        self.detectedLanguage = detectedLanguage
    }
}

public struct EngineStats: Codable, Sendable {
    public var cpuPercent: Float
    public var gpuPercent: Float
    public var vramUsedMb: Float
    public var ramUsedMb: Float

    nonisolated public init(cpuPercent: Float, gpuPercent: Float, vramUsedMb: Float, ramUsedMb: Float) {
        self.cpuPercent = cpuPercent
        self.gpuPercent = gpuPercent
        self.vramUsedMb = vramUsedMb
        self.ramUsedMb = ramUsedMb
    }
}

public struct CorrectionEdit: Codable, Sendable {
    public var editId: String
    public var spanStart: UInt32
    public var spanEnd: UInt32
    public var original: String
    public var replacement: String
    public var term: String
    public var aliasId: Int32
    public var rankerProb: Double
    public var gateProb: Double

    nonisolated public init(editId: String, spanStart: UInt32, spanEnd: UInt32, original: String, replacement: String, term: String, aliasId: Int32, rankerProb: Double, gateProb: Double) {
        self.editId = editId
        self.spanStart = spanStart
        self.spanEnd = spanEnd
        self.original = original
        self.replacement = replacement
        self.term = term
        self.aliasId = aliasId
        self.rankerProb = rankerProb
        self.gateProb = gateProb
    }
}

public struct CorrectionOutput: Codable, Sendable {
    public var sessionId: String
    public var bestText: String
    public var edits: [CorrectionEdit]

    nonisolated public init(sessionId: String, bestText: String, edits: [CorrectionEdit]) {
        self.sessionId = sessionId
        self.bestText = bestText
        self.edits = edits
    }
}

public struct EditResolution: Codable, Sendable {
    public var editId: String
    public var accepted: Bool

    nonisolated public init(editId: String, accepted: Bool) {
        self.editId = editId
        self.accepted = accepted
    }
}

// MARK: - Bee Encoders

nonisolated internal func encodeRepoFile(_ value: RepoFile, into buffer: inout ByteBuffer) {
    encodeString(value.name, into: &buffer)
    encodeString(value.url, into: &buffer)
}

nonisolated internal func encodeRepoDownload(_ value: RepoDownload, into buffer: inout ByteBuffer) {
    encodeString(value.repoId, into: &buffer)
    encodeString(value.localDir, into: &buffer)
    encodeVec(value.files, into: &buffer, encoder: { val, buf in encodeRepoFile(val, into: &buf) })
}

nonisolated internal func encodeBeeError(_ value: BeeError, into buffer: inout ByteBuffer) {
    switch value {
    case .engineNotLoaded:
        encodeVarint(UInt64(0), into: &buffer)
    case .sessionNotFound(let sessionId):
        encodeVarint(UInt64(1), into: &buffer)
        encodeString(sessionId, into: &buffer)
    case .loadFailed(let message):
        encodeVarint(UInt64(2), into: &buffer)
        encodeString(message, into: &buffer)
    case .transcriptionError(let message):
        encodeVarint(UInt64(3), into: &buffer)
        encodeString(message, into: &buffer)
    case .correctionError(let message):
        encodeVarint(UInt64(4), into: &buffer)
        encodeString(message, into: &buffer)
    case .notImplemented:
        encodeVarint(UInt64(5), into: &buffer)
    }
}

nonisolated internal func encodeSessionConfig(_ value: SessionConfig, into buffer: inout ByteBuffer) {
    encodeString(value.language, into: &buffer)
    encodeF32(value.chunkDuration, into: &buffer)
    encodeF32(value.vadThreshold, into: &buffer)
    encodeU32(value.rollbackTokens, into: &buffer)
    encodeU32(value.commitTokenCount, into: &buffer)
}

nonisolated internal func encodeAlignedWord(_ value: AlignedWord, into buffer: inout ByteBuffer) {
    encodeString(value.word, into: &buffer)
    encodeF64(value.start, into: &buffer)
    encodeF64(value.end, into: &buffer)
    encodeOption(value.meanLogprob, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
    encodeOption(value.minLogprob, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
    encodeOption(value.meanMargin, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
    encodeOption(value.minMargin, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
}

nonisolated internal func encodeFeedResult(_ value: FeedResult, into buffer: inout ByteBuffer) {
    encodeString(value.text, into: &buffer)
    encodeU32(value.committedUtf16Len, into: &buffer)
    encodeVec(value.alignments, into: &buffer, encoder: { val, buf in encodeAlignedWord(val, into: &buf) })
    encodeBool(value.isFinal, into: &buffer)
    encodeString(value.detectedLanguage, into: &buffer)
}

nonisolated internal func encodeEngineStats(_ value: EngineStats, into buffer: inout ByteBuffer) {
    encodeF32(value.cpuPercent, into: &buffer)
    encodeF32(value.gpuPercent, into: &buffer)
    encodeF32(value.vramUsedMb, into: &buffer)
    encodeF32(value.ramUsedMb, into: &buffer)
}

nonisolated internal func encodeCorrectionEdit(_ value: CorrectionEdit, into buffer: inout ByteBuffer) {
    encodeString(value.editId, into: &buffer)
    encodeU32(value.spanStart, into: &buffer)
    encodeU32(value.spanEnd, into: &buffer)
    encodeString(value.original, into: &buffer)
    encodeString(value.replacement, into: &buffer)
    encodeString(value.term, into: &buffer)
    encodeI32(value.aliasId, into: &buffer)
    encodeF64(value.rankerProb, into: &buffer)
    encodeF64(value.gateProb, into: &buffer)
}

nonisolated internal func encodeCorrectionOutput(_ value: CorrectionOutput, into buffer: inout ByteBuffer) {
    encodeString(value.sessionId, into: &buffer)
    encodeString(value.bestText, into: &buffer)
    encodeVec(value.edits, into: &buffer, encoder: { val, buf in encodeCorrectionEdit(val, into: &buf) })
}

nonisolated internal func encodeEditResolution(_ value: EditResolution, into buffer: inout ByteBuffer) {
    encodeString(value.editId, into: &buffer)
    encodeBool(value.accepted, into: &buffer)
}
// MARK: - Bee Client

///  The main bee service — replaces all C FFI.
///  Swift (initiator/client) talks to Rust (acceptor/server) over vox-ffi.
public protocol BeeCaller {
    ///  Full manifest of all required model repos.
    func requiredDownloads() async throws -> [RepoDownload]
    ///  Load ASR engine from the given cache dir.
    func loadEngine(cacheDir: String) async throws -> Result<Bool, BeeError>
    ///  Create a transcription session, returns session ID.
    func createSession(opts: SessionConfig) async throws -> Result<String, BeeError>
    ///  Feed audio samples to a session.
    func feed(sessionId: String, samples: [Float]) async throws -> Result<FeedResult?, BeeError>
    ///  Finalize a session, returns final transcription with alignments.
    func finishSession(sessionId: String) async throws -> Result<FeedResult, BeeError>
    ///  Set the language for a session.
    func setLanguage(sessionId: String, language: String) async throws -> Result<Bool, BeeError>
    ///  Single-shot transcription of raw 16kHz f32 samples.
    func transcribeSamples(samples: [Float]) async throws -> Result<String, BeeError>
    ///  Get engine resource usage stats.
    func getStats() async throws -> EngineStats
    ///  Load the correction engine.
    func correctLoad(datasetDir: String, eventsPath: String, gateThreshold: Float, rankerThreshold: Float) async throws -> Result<Bool, BeeError>
    ///  Run correction on text with per-word ASR confidence data.
    func correctProcess(text: String, appId: String, words: [AlignedWord]) async throws -> CorrectionOutput
    ///  Teach the correction engine from user resolutions.
    func correctTeach(sessionId: String, resolutions: [EditResolution]) async throws -> Result<Bool, BeeError>
    ///  Save correction engine state to disk.
    func correctSave() async throws -> Result<Bool, BeeError>
}

public final class BeeClient: BeeCaller, Sendable {
    private let connection: VoxConnection
    private let timeout: TimeInterval?

    public init(connection: VoxConnection, timeout: TimeInterval? = 30.0) {
        self.connection = connection
        self.timeout = timeout
    }

    public func requiredDownloads() async throws -> [RepoDownload] {
        let payload: [UInt8] = []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xec7becd2deb1dad4]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xec7becd2deb1dad4, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeInfallibleResponse(response) { buf in
            let result = try decodeVec(from: &buf, decoder: { buf in
                let _repoId = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _localDir = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _files = try ({ buf in try decodeVec(from: &buf, decoder: { buf in
                let _name = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _url = try ({ buf in try decodeString(from: &buf) })(&buf)
                return RepoFile(name: _name, url: _url)
            }) })(&buf)
                return RepoDownload(repoId: _repoId, localDir: _localDir, files: _files)
            })
            return result
        }
    }

    public func loadEngine(cacheDir: String) async throws -> Result<Bool, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(cacheDir, into: &buffer)
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0x1c123a5c2762d6a5]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0x1c123a5c2762d6a5, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeBool(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func createSession(opts: SessionConfig) async throws -> Result<String, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeSessionConfig(opts, into: &buffer)
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xed77a6d793863a25]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xed77a6d793863a25, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeString(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func feed(sessionId: String, samples: [Float]) async throws -> Result<FeedResult?, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(sessionId, into: &buffer)
        encodeVec(samples, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xc7e28a8816c1bc83]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xc7e28a8816c1bc83, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeOption(from: &buf, decoder: { buf in
                    let _text = try ({ buf in try decodeString(from: &buf) })(&buf)
                    let _committedUtf16Len = try ({ buf in try decodeU32(from: &buf) })(&buf)
                    let _alignments = try ({ buf in try decodeVec(from: &buf, decoder: { buf in
                    let _word = try ({ buf in try decodeString(from: &buf) })(&buf)
                    let _start = try ({ buf in try decodeF64(from: &buf) })(&buf)
                    let _end = try ({ buf in try decodeF64(from: &buf) })(&buf)
                    let _meanLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _minLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _meanMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _minMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    return AlignedWord(word: _word, start: _start, end: _end, meanLogprob: _meanLogprob, minLogprob: _minLogprob, meanMargin: _meanMargin, minMargin: _minMargin)
                }) })(&buf)
                    let _isFinal = try ({ buf in try decodeBool(from: &buf) })(&buf)
                    let _detectedLanguage = try ({ buf in try decodeString(from: &buf) })(&buf)
                    return FeedResult(text: _text, committedUtf16Len: _committedUtf16Len, alignments: _alignments, isFinal: _isFinal, detectedLanguage: _detectedLanguage)
                })
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func finishSession(sessionId: String) async throws -> Result<FeedResult, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(sessionId, into: &buffer)
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0x416a48f228b25310]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0x416a48f228b25310, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let _value_text = try decodeString(from: &buf)
                let _value_committedUtf16Len = try decodeU32(from: &buf)
                let _value_alignments = try decodeVec(from: &buf, decoder: { buf in
                    let _word = try ({ buf in try decodeString(from: &buf) })(&buf)
                    let _start = try ({ buf in try decodeF64(from: &buf) })(&buf)
                    let _end = try ({ buf in try decodeF64(from: &buf) })(&buf)
                    let _meanLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _minLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _meanMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    let _minMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                    return AlignedWord(word: _word, start: _start, end: _end, meanLogprob: _meanLogprob, minLogprob: _minLogprob, meanMargin: _meanMargin, minMargin: _minMargin)
                })
                let _value_isFinal = try decodeBool(from: &buf)
                let _value_detectedLanguage = try decodeString(from: &buf)
                let value = FeedResult(text: _value_text, committedUtf16Len: _value_committedUtf16Len, alignments: _value_alignments, isFinal: _value_isFinal, detectedLanguage: _value_detectedLanguage)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func setLanguage(sessionId: String, language: String) async throws -> Result<Bool, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(sessionId, into: &buffer)
        encodeString(language, into: &buffer)
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xefb09d27037e41ed]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xefb09d27037e41ed, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeBool(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func transcribeSamples(samples: [Float]) async throws -> Result<String, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeVec(samples, into: &buffer, encoder: { val, buf in encodeF32(val, into: &buf) })
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xbb649049c66f9f90]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xbb649049c66f9f90, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeString(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func getStats() async throws -> EngineStats {
        let payload: [UInt8] = []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xac27f8b9cda1c89f]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xac27f8b9cda1c89f, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeInfallibleResponse(response) { buf in
            let _result_cpuPercent = try decodeF32(from: &buf)
            let _result_gpuPercent = try decodeF32(from: &buf)
            let _result_vramUsedMb = try decodeF32(from: &buf)
            let _result_ramUsedMb = try decodeF32(from: &buf)
            let result = EngineStats(cpuPercent: _result_cpuPercent, gpuPercent: _result_gpuPercent, vramUsedMb: _result_vramUsedMb, ramUsedMb: _result_ramUsedMb)
            return result
        }
    }

    public func correctLoad(datasetDir: String, eventsPath: String, gateThreshold: Float, rankerThreshold: Float) async throws -> Result<Bool, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(datasetDir, into: &buffer)
        encodeString(eventsPath, into: &buffer)
        encodeF32(gateThreshold, into: &buffer)
        encodeF32(rankerThreshold, into: &buffer)
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xc6ef90e080c66309]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xc6ef90e080c66309, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeBool(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func correctProcess(text: String, appId: String, words: [AlignedWord]) async throws -> CorrectionOutput {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(text, into: &buffer)
        encodeString(appId, into: &buffer)
        encodeVec(words, into: &buffer, encoder: { val, buf in encodeAlignedWord(val, into: &buf) })
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xd383d61a2c875e84]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xd383d61a2c875e84, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeInfallibleResponse(response) { buf in
            let _result_sessionId = try decodeString(from: &buf)
            let _result_bestText = try decodeString(from: &buf)
            let _result_edits = try decodeVec(from: &buf, decoder: { buf in
                let _editId = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _spanStart = try ({ buf in try decodeU32(from: &buf) })(&buf)
                let _spanEnd = try ({ buf in try decodeU32(from: &buf) })(&buf)
                let _original = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _replacement = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _term = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _aliasId = try ({ buf in try decodeI32(from: &buf) })(&buf)
                let _rankerProb = try ({ buf in try decodeF64(from: &buf) })(&buf)
                let _gateProb = try ({ buf in try decodeF64(from: &buf) })(&buf)
                return CorrectionEdit(editId: _editId, spanStart: _spanStart, spanEnd: _spanEnd, original: _original, replacement: _replacement, term: _term, aliasId: _aliasId, rankerProb: _rankerProb, gateProb: _gateProb)
            })
            let result = CorrectionOutput(sessionId: _result_sessionId, bestText: _result_bestText, edits: _result_edits)
            return result
        }
    }

    public func correctTeach(sessionId: String, resolutions: [EditResolution]) async throws -> Result<Bool, BeeError> {
        var buffer = ByteBufferAllocator().buffer(capacity: 64)
        encodeString(sessionId, into: &buffer)
        encodeVec(resolutions, into: &buffer, encoder: { val, buf in encodeEditResolution(val, into: &buf) })
        let payload = buffer.readBytes(length: buffer.readableBytes) ?? []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0x2163f1014480c2db]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0x2163f1014480c2db, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeBool(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }

    public func correctSave() async throws -> Result<Bool, BeeError> {
        let payload: [UInt8] = []
        let schemaInfo = ClientSchemaInfo(methodInfo: bee_method_schemas[0xa5b4730fb9dbaa99]!, schemaRegistry: bee_schema_registry)
        let response = try await connection.call(methodId: 0xa5b4730fb9dbaa99, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        return try decodeFallibleResponse(response,
            decodeOk: { buf in
                let value = try decodeBool(from: &buf)
                return value
            },
            decodeErr: { buf in
                let _userError_disc = try decodeVarint(from: &buf)
                let userError: BeeError
                switch _userError_disc {
                case 0:
                    userError = .engineNotLoaded
                case 1:
                    let _userError_sessionId = try decodeString(from: &buf)
                    userError = .sessionNotFound(sessionId: _userError_sessionId)
                case 2:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .loadFailed(message: _userError_message)
                case 3:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .transcriptionError(message: _userError_message)
                case 4:
                    let _userError_message = try decodeString(from: &buf)
                    userError = .correctionError(message: _userError_message)
                case 5:
                    userError = .notImplemented
                default:
                    throw VoxError.decodeError("unknown enum variant")
                }
                return userError
            })
    }
}

// MARK: - Bee Server

///  The main bee service — replaces all C FFI.
///  Swift (initiator/client) talks to Rust (acceptor/server) over vox-ffi.
public protocol BeeHandler: Sendable {
    ///  Full manifest of all required model repos.
    func requiredDownloads() async throws -> [RepoDownload]
    ///  Load ASR engine from the given cache dir.
    func loadEngine(cacheDir: String) async throws -> Result<Bool, BeeError>
    ///  Create a transcription session, returns session ID.
    func createSession(opts: SessionConfig) async throws -> Result<String, BeeError>
    ///  Feed audio samples to a session.
    func feed(sessionId: String, samples: [Float]) async throws -> Result<FeedResult?, BeeError>
    ///  Finalize a session, returns final transcription with alignments.
    func finishSession(sessionId: String) async throws -> Result<FeedResult, BeeError>
    ///  Set the language for a session.
    func setLanguage(sessionId: String, language: String) async throws -> Result<Bool, BeeError>
    ///  Single-shot transcription of raw 16kHz f32 samples.
    func transcribeSamples(samples: [Float]) async throws -> Result<String, BeeError>
    ///  Get engine resource usage stats.
    func getStats() async throws -> EngineStats
    ///  Load the correction engine.
    func correctLoad(datasetDir: String, eventsPath: String, gateThreshold: Float, rankerThreshold: Float) async throws -> Result<Bool, BeeError>
    ///  Run correction on text with per-word ASR confidence data.
    func correctProcess(text: String, appId: String, words: [AlignedWord]) async throws -> CorrectionOutput
    ///  Teach the correction engine from user resolutions.
    func correctTeach(sessionId: String, resolutions: [EditResolution]) async throws -> Result<Bool, BeeError>
    ///  Save correction engine state to disk.
    func correctSave() async throws -> Result<Bool, BeeError>
}

public final class BeeDispatcher: ServiceDispatcher {
    private let handler: BeeHandler
    private let schemaRegistry: [UInt64: Schema]
    private let methodSchemas: [UInt64: MethodSchemaInfo]

    public init(handler: BeeHandler, schemaRegistry: [UInt64: Schema] = bee_schema_registry, methodSchemas: [UInt64: MethodSchemaInfo] = bee_method_schemas) {
        self.handler = handler
        self.schemaRegistry = schemaRegistry
        self.methodSchemas = methodSchemas
    }

    public func dispatch(methodId: UInt64, payload: [UInt8], requestId: UInt64, registry: ChannelRegistry, schemaSendTracker _: SchemaSendTracker, taskTx: @escaping @Sendable (TaskMessage) -> Void) async {
        var buffer = ByteBufferAllocator().buffer(capacity: payload.count)
        buffer.writeBytes(payload)
        let taskSender: TaskSender = taskTx
        switch methodId {
        case 0xec7becd2deb1dad4:
            await dispatch_requiredDownloads(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0x1c123a5c2762d6a5:
            await dispatch_loadEngine(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xed77a6d793863a25:
            await dispatch_createSession(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xc7e28a8816c1bc83:
            await dispatch_feed(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0x416a48f228b25310:
            await dispatch_finishSession(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xefb09d27037e41ed:
            await dispatch_setLanguage(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xbb649049c66f9f90:
            await dispatch_transcribeSamples(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xac27f8b9cda1c89f:
            await dispatch_getStats(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xc6ef90e080c66309:
            await dispatch_correctLoad(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xd383d61a2c875e84:
            await dispatch_correctProcess(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0x2163f1014480c2db:
            await dispatch_correctTeach(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        case 0xa5b4730fb9dbaa99:
            await dispatch_correctSave(methodId: methodId, requestId: requestId, buffer: &buffer, registry: registry, taskSender: taskSender)
        default:
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
        }
    }

    public func retryPolicy(methodId: UInt64) -> RetryPolicy {
        switch methodId {
        case 0xec7becd2deb1dad4:
            return .volatile
        case 0x1c123a5c2762d6a5:
            return .volatile
        case 0xed77a6d793863a25:
            return .volatile
        case 0xc7e28a8816c1bc83:
            return .volatile
        case 0x416a48f228b25310:
            return .volatile
        case 0xefb09d27037e41ed:
            return .volatile
        case 0xbb649049c66f9f90:
            return .volatile
        case 0xac27f8b9cda1c89f:
            return .volatile
        case 0xc6ef90e080c66309:
            return .volatile
        case 0xd383d61a2c875e84:
            return .volatile
        case 0x2163f1014480c2db:
            return .volatile
        case 0xa5b4730fb9dbaa99:
            return .volatile
        default:
            return .volatile
        }
    }

    /// Pre-register Rx channel IDs from request payloads.
    /// Call this synchronously before spawning the dispatch task to avoid
    /// race conditions where Data arrives before channels are registered.
    public func preregister(methodId: UInt64, payload: [UInt8], registry: ChannelRegistry) async {
        var buffer = ByteBufferAllocator().buffer(capacity: payload.count)
        buffer.writeBytes(payload)
        switch methodId {
        default:
            break
        }
    }

    private func dispatch_requiredDownloads(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.requiredDownloads()
                let _encoded = encodeResultOk(result, encoder: { val, buf in encodeVec(val, into: &buf, encoder: { val, buf in encodeRepoDownload(val, into: &buf) }) })
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_loadEngine(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let cacheDir = try decodeString(from: &buffer)
            do {
                let result = try await handler.loadEngine(cacheDir: cacheDir)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeBool(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_createSession(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let _opts_language = try decodeString(from: &buffer)
            let _opts_chunkDuration = try decodeF32(from: &buffer)
            let _opts_vadThreshold = try decodeF32(from: &buffer)
            let _opts_rollbackTokens = try decodeU32(from: &buffer)
            let _opts_commitTokenCount = try decodeU32(from: &buffer)
            let opts = SessionConfig(language: _opts_language, chunkDuration: _opts_chunkDuration, vadThreshold: _opts_vadThreshold, rollbackTokens: _opts_rollbackTokens, commitTokenCount: _opts_commitTokenCount)
            do {
                let result = try await handler.createSession(opts: opts)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeString(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_feed(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let sessionId = try decodeString(from: &buffer)
            let samples = try decodeVec(from: &buffer, decoder: { buf in try decodeF32(from: &buf) })
            do {
                let result = try await handler.feed(sessionId: sessionId, samples: samples)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeOption(v, into: &buffer, encoder: { val, buf in encodeFeedResult(val, into: &buf) })
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_finishSession(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let sessionId = try decodeString(from: &buffer)
            do {
                let result = try await handler.finishSession(sessionId: sessionId)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeFeedResult(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_setLanguage(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let sessionId = try decodeString(from: &buffer)
            let language = try decodeString(from: &buffer)
            do {
                let result = try await handler.setLanguage(sessionId: sessionId, language: language)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeBool(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_transcribeSamples(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let samples = try decodeVec(from: &buffer, decoder: { buf in try decodeF32(from: &buf) })
            do {
                let result = try await handler.transcribeSamples(samples: samples)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeString(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_getStats(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.getStats()
                let _encoded = encodeResultOk(result, encoder: { val, buf in encodeEngineStats(val, into: &buf) })
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_correctLoad(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let datasetDir = try decodeString(from: &buffer)
            let eventsPath = try decodeString(from: &buffer)
            let gateThreshold = try decodeF32(from: &buffer)
            let rankerThreshold = try decodeF32(from: &buffer)
            do {
                let result = try await handler.correctLoad(datasetDir: datasetDir, eventsPath: eventsPath, gateThreshold: gateThreshold, rankerThreshold: rankerThreshold)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeBool(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_correctProcess(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let text = try decodeString(from: &buffer)
            let appId = try decodeString(from: &buffer)
            let words = try decodeVec(from: &buffer, decoder: { buf in
                let _word = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _start = try ({ buf in try decodeF64(from: &buf) })(&buf)
                let _end = try ({ buf in try decodeF64(from: &buf) })(&buf)
                let _meanLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                let _minLogprob = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                let _meanMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                let _minMargin = try ({ buf in try decodeOption(from: &buf, decoder: { buf in try decodeF32(from: &buf) }) })(&buf)
                return AlignedWord(word: _word, start: _start, end: _end, meanLogprob: _meanLogprob, minLogprob: _minLogprob, meanMargin: _meanMargin, minMargin: _minMargin)
            })
            do {
                let result = try await handler.correctProcess(text: text, appId: appId, words: words)
                let _encoded = encodeResultOk(result, encoder: { val, buf in encodeCorrectionOutput(val, into: &buf) })
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_correctTeach(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            let sessionId = try decodeString(from: &buffer)
            let resolutions = try decodeVec(from: &buffer, decoder: { buf in
                let _editId = try ({ buf in try decodeString(from: &buf) })(&buf)
                let _accepted = try ({ buf in try decodeBool(from: &buf) })(&buf)
                return EditResolution(editId: _editId, accepted: _accepted)
            })
            do {
                let result = try await handler.correctTeach(sessionId: sessionId, resolutions: resolutions)
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeBool(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_correctSave(methodId: UInt64, requestId: UInt64, buffer: inout ByteBuffer, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            do {
                let result = try await handler.correctSave()
                let _encoded: [UInt8] = {
                    var buffer = ByteBufferAllocator().buffer(capacity: 64)
                    switch result {
                    case .success(let v):
                        encodeVarint(UInt64(0), into: &buffer)
                        encodeBool(v, into: &buffer)
                    case .failure(let e):
                        encodeVarint(UInt64(1), into: &buffer)
                        encodeU8(0, into: &buffer)
                        encodeBeeError(e, into: &buffer)
                    }
                    return buffer.readBytes(length: buffer.readableBytes) ?? []
                }()
                taskSender(.response(requestId: requestId, payload: _encoded, methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

}

// MARK: - Bee Schemas

public let bee_schemas: [String: MethodBindingSchema] = [
    "requiredDownloads": MethodBindingSchema(args: []),
    "loadEngine": MethodBindingSchema(args: [.string]),
    "createSession": MethodBindingSchema(args: [.struct(fields: [("language", .string), ("chunk_duration", .f32), ("vad_threshold", .f32), ("rollback_tokens", .u32), ("commit_token_count", .u32)])]),
    "feed": MethodBindingSchema(args: [.string, .vec(element: .f32)]),
    "finishSession": MethodBindingSchema(args: [.string]),
    "setLanguage": MethodBindingSchema(args: [.string, .string]),
    "transcribeSamples": MethodBindingSchema(args: [.vec(element: .f32)]),
    "getStats": MethodBindingSchema(args: []),
    "correctLoad": MethodBindingSchema(args: [.string, .string, .f32, .f32]),
    "correctProcess": MethodBindingSchema(args: [.string, .string, .vec(element: .struct(fields: [("word", .string), ("start", .f64), ("end", .f64), ("mean_logprob", .option(inner: .f32)), ("min_logprob", .option(inner: .f32)), ("mean_margin", .option(inner: .f32)), ("min_margin", .option(inner: .f32))]))]),
    "correctTeach": MethodBindingSchema(args: [.string, .vec(element: .struct(fields: [("edit_id", .string), ("accepted", .bool)]))]),
    "correctSave": MethodBindingSchema(args: []),
]

/// Global schema registry containing all schemas for this service.
nonisolated(unsafe) public let bee_schema_registry: [UInt64: Schema] = [
    0x082890bfae12d841: Schema(id: 0x082890bfae12d841, typeParams: [], kind: .struct(name: "RepoDownload", fields: [FieldSchema(name: "repo_id", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "local_dir", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "files", typeRef: .generic(0x0a96b404b4d79d67, args: [.concrete(0x3c1d05e5924fa784)]), required: true)])),
    0x0a96b404b4d79d67: Schema(id: 0x0a96b404b4d79d67, typeParams: ["T"], kind: .list(element: .var(name: "T"))),
    0x178367a87f66fb46: Schema(id: 0x178367a87f66fb46, typeParams: [], kind: .primitive(.bool)),
    0x281c5be4f2ee63b4: Schema(id: 0x281c5be4f2ee63b4, typeParams: [], kind: .primitive(.u32)),
    0x285872d3b3eded20: Schema(id: 0x285872d3b3eded20, typeParams: [], kind: .enum(name: "BeeError", variants: [VariantSchema(name: "EngineNotLoaded", index: 0, payload: .unit), VariantSchema(name: "SessionNotFound", index: 1, payload: .struct(fields: [FieldSchema(name: "session_id", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])), VariantSchema(name: "LoadFailed", index: 2, payload: .struct(fields: [FieldSchema(name: "message", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])), VariantSchema(name: "TranscriptionError", index: 3, payload: .struct(fields: [FieldSchema(name: "message", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])), VariantSchema(name: "CorrectionError", index: 4, payload: .struct(fields: [FieldSchema(name: "message", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])), VariantSchema(name: "NotImplemented", index: 5, payload: .unit)])),
    0x361f4536eee9f991: Schema(id: 0x361f4536eee9f991, typeParams: [], kind: .primitive(.i32)),
    0x3c1d05e5924fa784: Schema(id: 0x3c1d05e5924fa784, typeParams: [], kind: .struct(name: "RepoFile", fields: [FieldSchema(name: "name", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "url", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])),
    0x3f2e589db81e95bf: Schema(id: 0x3f2e589db81e95bf, typeParams: [], kind: .primitive(.f64)),
    0x42046de663beeef0: Schema(id: 0x42046de663beeef0, typeParams: ["T", "E"], kind: .enum(name: "Result", variants: [VariantSchema(name: "Ok", index: 0, payload: .newtype(typeRef: .var(name: "T"))), VariantSchema(name: "Err", index: 1, payload: .newtype(typeRef: .var(name: "E")))])),
    0x4cf4b2aeb98a1939: Schema(id: 0x4cf4b2aeb98a1939, typeParams: ["E"], kind: .enum(name: "VoxError", variants: [VariantSchema(name: "User", index: 0, payload: .newtype(typeRef: .var(name: "E"))), VariantSchema(name: "UnknownMethod", index: 1, payload: .unit), VariantSchema(name: "InvalidPayload", index: 2, payload: .newtype(typeRef: .concrete(0x6d7dce914ee150e8))), VariantSchema(name: "Cancelled", index: 3, payload: .unit), VariantSchema(name: "ConnectionClosed", index: 4, payload: .unit), VariantSchema(name: "SessionShutdown", index: 5, payload: .unit), VariantSchema(name: "SendFailed", index: 6, payload: .unit), VariantSchema(name: "Indeterminate", index: 7, payload: .unit)])),
    0x5c000f00fa144db4: Schema(id: 0x5c000f00fa144db4, typeParams: [], kind: .struct(name: "CorrectionEdit", fields: [FieldSchema(name: "edit_id", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "span_start", typeRef: .concrete(0x281c5be4f2ee63b4), required: true), FieldSchema(name: "span_end", typeRef: .concrete(0x281c5be4f2ee63b4), required: true), FieldSchema(name: "original", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "replacement", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "term", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "alias_id", typeRef: .concrete(0x361f4536eee9f991), required: true), FieldSchema(name: "ranker_prob", typeRef: .concrete(0x3f2e589db81e95bf), required: true), FieldSchema(name: "gate_prob", typeRef: .concrete(0x3f2e589db81e95bf), required: true)])),
    0x5db70a394660f3e6: Schema(id: 0x5db70a394660f3e6, typeParams: [], kind: .primitive(.never)),
    0x6847ab90feda71c1: Schema(id: 0x6847ab90feda71c1, typeParams: ["T0"], kind: .tuple(elements: [.var(name: "T0")])),
    0x6a31d1dd6bec4d20: Schema(id: 0x6a31d1dd6bec4d20, typeParams: [], kind: .struct(name: "CorrectionOutput", fields: [FieldSchema(name: "session_id", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "best_text", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "edits", typeRef: .generic(0x0a96b404b4d79d67, args: [.concrete(0x5c000f00fa144db4)]), required: true)])),
    0x6d7dce914ee150e8: Schema(id: 0x6d7dce914ee150e8, typeParams: [], kind: .primitive(.string)),
    0x6ec4adf14402f13d: Schema(id: 0x6ec4adf14402f13d, typeParams: [], kind: .struct(name: "EngineStats", fields: [FieldSchema(name: "cpu_percent", typeRef: .concrete(0x8e02f623d1b2310c), required: true), FieldSchema(name: "gpu_percent", typeRef: .concrete(0x8e02f623d1b2310c), required: true), FieldSchema(name: "vram_used_mb", typeRef: .concrete(0x8e02f623d1b2310c), required: true), FieldSchema(name: "ram_used_mb", typeRef: .concrete(0x8e02f623d1b2310c), required: true)])),
    0x715e96e611ad7d16: Schema(id: 0x715e96e611ad7d16, typeParams: [], kind: .struct(name: "SessionConfig", fields: [FieldSchema(name: "language", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "chunk_duration", typeRef: .concrete(0x8e02f623d1b2310c), required: true), FieldSchema(name: "vad_threshold", typeRef: .concrete(0x8e02f623d1b2310c), required: true), FieldSchema(name: "rollback_tokens", typeRef: .concrete(0x281c5be4f2ee63b4), required: true), FieldSchema(name: "commit_token_count", typeRef: .concrete(0x281c5be4f2ee63b4), required: true)])),
    0x8e02f623d1b2310c: Schema(id: 0x8e02f623d1b2310c, typeParams: [], kind: .primitive(.f32)),
    0x915c6fb5b64f270b: Schema(id: 0x915c6fb5b64f270b, typeParams: ["T0", "T1", "T2", "T3"], kind: .tuple(elements: [.var(name: "T0"), .var(name: "T1"), .var(name: "T2"), .var(name: "T3")])),
    0x9d430384fa68b98c: Schema(id: 0x9d430384fa68b98c, typeParams: [], kind: .struct(name: "FeedResult", fields: [FieldSchema(name: "text", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "committed_utf16_len", typeRef: .concrete(0x281c5be4f2ee63b4), required: true), FieldSchema(name: "alignments", typeRef: .generic(0x0a96b404b4d79d67, args: [.concrete(0xf0d30c1c928667ef)]), required: true), FieldSchema(name: "is_final", typeRef: .concrete(0x178367a87f66fb46), required: true), FieldSchema(name: "detected_language", typeRef: .concrete(0x6d7dce914ee150e8), required: true)])),
    0xaa510ab07d34f141: Schema(id: 0xaa510ab07d34f141, typeParams: ["T0", "T1", "T2"], kind: .tuple(elements: [.var(name: "T0"), .var(name: "T1"), .var(name: "T2")])),
    0xba0496aa8cee7a4c: Schema(id: 0xba0496aa8cee7a4c, typeParams: ["T0", "T1"], kind: .tuple(elements: [.var(name: "T0"), .var(name: "T1")])),
    0xbc5c33249a2dc720: Schema(id: 0xbc5c33249a2dc720, typeParams: [], kind: .primitive(.unit)),
    0xdcafd4de6b7969bb: Schema(id: 0xdcafd4de6b7969bb, typeParams: ["T"], kind: .option(element: .var(name: "T"))),
    0xf0d30c1c928667ef: Schema(id: 0xf0d30c1c928667ef, typeParams: [], kind: .struct(name: "AlignedWord", fields: [FieldSchema(name: "word", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "start", typeRef: .concrete(0x3f2e589db81e95bf), required: true), FieldSchema(name: "end", typeRef: .concrete(0x3f2e589db81e95bf), required: true), FieldSchema(name: "mean_logprob", typeRef: .generic(0xdcafd4de6b7969bb, args: [.concrete(0x8e02f623d1b2310c)]), required: true), FieldSchema(name: "min_logprob", typeRef: .generic(0xdcafd4de6b7969bb, args: [.concrete(0x8e02f623d1b2310c)]), required: true), FieldSchema(name: "mean_margin", typeRef: .generic(0xdcafd4de6b7969bb, args: [.concrete(0x8e02f623d1b2310c)]), required: true), FieldSchema(name: "min_margin", typeRef: .generic(0xdcafd4de6b7969bb, args: [.concrete(0x8e02f623d1b2310c)]), required: true)])),
    0xf92331d26d0aabc4: Schema(id: 0xf92331d26d0aabc4, typeParams: [], kind: .struct(name: "EditResolution", fields: [FieldSchema(name: "edit_id", typeRef: .concrete(0x6d7dce914ee150e8), required: true), FieldSchema(name: "accepted", typeRef: .concrete(0x178367a87f66fb46), required: true)])),
]

/// Per-method schema information for wire protocol.
nonisolated(unsafe) public let bee_method_schemas: [UInt64: MethodSchemaInfo] = [
    0xec7becd2deb1dad4: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x3c1d05e5924fa784, 0x0a96b404b4d79d67, 0x082890bfae12d841],
        responseRoot: .generic(0x42046de663beeef0, args: [.generic(0x0a96b404b4d79d67, args: [.concrete(0x082890bfae12d841)]), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x1c123a5c2762d6a5: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xed77a6d793863a25: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x8e02f623d1b2310c, 0x281c5be4f2ee63b4, 0x715e96e611ad7d16, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x715e96e611ad7d16)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6d7dce914ee150e8), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xc7e28a8816c1bc83: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x8e02f623d1b2310c, 0x0a96b404b4d79d67, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .generic(0x0a96b404b4d79d67, args: [.concrete(0x8e02f623d1b2310c)])]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x3f2e589db81e95bf, 0x8e02f623d1b2310c, 0xdcafd4de6b7969bb, 0xf0d30c1c928667ef, 0x0a96b404b4d79d67, 0x9d430384fa68b98c, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.generic(0xdcafd4de6b7969bb, args: [.concrete(0x9d430384fa68b98c)]), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0x416a48f228b25310: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x3f2e589db81e95bf, 0x8e02f623d1b2310c, 0xdcafd4de6b7969bb, 0xf0d30c1c928667ef, 0x0a96b404b4d79d67, 0x9d430384fa68b98c, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x9d430384fa68b98c), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xefb09d27037e41ed: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xbb649049c66f9f90: MethodSchemaInfo(
        argsSchemaIds: [0x8e02f623d1b2310c, 0x0a96b404b4d79d67, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.generic(0x0a96b404b4d79d67, args: [.concrete(0x8e02f623d1b2310c)])]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6d7dce914ee150e8), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xac27f8b9cda1c89f: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x8e02f623d1b2310c, 0x6ec4adf14402f13d],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6ec4adf14402f13d), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0xc6ef90e080c66309: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x8e02f623d1b2310c, 0x915c6fb5b64f270b],
        argsRoot: .generic(0x915c6fb5b64f270b, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8), .concrete(0x8e02f623d1b2310c), .concrete(0x8e02f623d1b2310c)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xd383d61a2c875e84: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x3f2e589db81e95bf, 0x8e02f623d1b2310c, 0xdcafd4de6b7969bb, 0xf0d30c1c928667ef, 0x0a96b404b4d79d67, 0xaa510ab07d34f141],
        argsRoot: .generic(0xaa510ab07d34f141, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8), .generic(0x0a96b404b4d79d67, args: [.concrete(0xf0d30c1c928667ef)])]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x361f4536eee9f991, 0x3f2e589db81e95bf, 0x5c000f00fa144db4, 0x0a96b404b4d79d67, 0x6a31d1dd6bec4d20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x6a31d1dd6bec4d20), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x2163f1014480c2db: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x178367a87f66fb46, 0xf92331d26d0aabc4, 0x0a96b404b4d79d67, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .generic(0x0a96b404b4d79d67, args: [.concrete(0xf92331d26d0aabc4)])]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
    0xa5b4730fb9dbaa99: MethodSchemaInfo(
        argsSchemaIds: [0xbc5c33249a2dc720],
        argsRoot: .concrete(0xbc5c33249a2dc720),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939, 0x285872d3b3eded20],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x285872d3b3eded20)])])
    ),
]

public struct BeeSerializers: BindingSerializers {
    public init() {}

    public func txSerializer(for schema: BindingSchema) -> @Sendable (Any) -> [UInt8] {
        switch schema {
        case .bool: return { var b = ByteBufferAllocator().buffer(capacity: 1); encodeBool($0 as! Bool, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .u8: return { var b = ByteBufferAllocator().buffer(capacity: 1); encodeU8($0 as! UInt8, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .i8: return { var b = ByteBufferAllocator().buffer(capacity: 1); encodeI8($0 as! Int8, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .u16: return { var b = ByteBufferAllocator().buffer(capacity: 2); encodeU16($0 as! UInt16, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .i16: return { var b = ByteBufferAllocator().buffer(capacity: 2); encodeI16($0 as! Int16, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .u32: return { var b = ByteBufferAllocator().buffer(capacity: 4); encodeU32($0 as! UInt32, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .i32: return { var b = ByteBufferAllocator().buffer(capacity: 4); encodeI32($0 as! Int32, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .u64: return { var b = ByteBufferAllocator().buffer(capacity: 9); encodeVarint($0 as! UInt64, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .i64: return { var b = ByteBufferAllocator().buffer(capacity: 9); encodeI64($0 as! Int64, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .f32: return { var b = ByteBufferAllocator().buffer(capacity: 4); encodeF32($0 as! Float, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .f64: return { var b = ByteBufferAllocator().buffer(capacity: 8); encodeF64($0 as! Double, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .string: return { var b = ByteBufferAllocator().buffer(capacity: 64); encodeString($0 as! String, into: &b); return b.readBytes(length: b.readableBytes) ?? [] }
        case .bytes: return { [UInt8]($0 as! Data) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not serialized directly")
        default: fatalError("Unsupported schema for Tx serialization: \(schema)")
        }
    }

    public func rxDeserializer(for schema: BindingSchema) -> @Sendable ([UInt8]) throws -> Any {
        switch schema {
        case .bool: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeBool(from: &b) }
        case .u8: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeU8(from: &b) }
        case .i8: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeI8(from: &b) }
        case .u16: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeU16(from: &b) }
        case .i16: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeI16(from: &b) }
        case .u32: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeU32(from: &b) }
        case .i32: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeI32(from: &b) }
        case .u64: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeVarint(from: &b) }
        case .i64: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeI64(from: &b) }
        case .f32: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeF32(from: &b) }
        case .f64: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeF64(from: &b) }
        case .string: return { var b = ByteBufferAllocator().buffer(bytes: $0); return try decodeString(from: &b) }
        case .bytes: return { Data($0) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not deserialized directly")
        default: fatalError("Unsupported schema for Rx deserialization: \(schema)")
        }
    }
}

