// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import Foundation
import VoxRuntime

// MARK: - Ime Method IDs

public enum ImeMethodId {
    public static let setMarkedText: UInt64 = 0x2d335085427db481
    public static let commitText: UInt64 = 0x5716af924e8ded0f
    public static let stopDictating: UInt64 = 0x68519c24d46321b4
    public static let prepareSession: UInt64 = 0x237826434890468a
}

// MARK: - Ime Types

// MARK: - Ime Client

///  Methods the IME exposes — app calls into IME.
public protocol ImeCaller {
    ///  App sends marked text to the IME for display.
    func setMarkedText(sessionId: String, text: String) async throws -> Bool
    ///  App tells IME to commit text and end the session.
    func commitText(sessionId: String, text: String) async throws -> Bool
    ///  App tells IME to stop dictating (cancel/abort).
    func stopDictating(sessionId: String) async throws -> Bool
    ///  App pushes a prepared session to the IME. IME should claim it
    ///  when activateServer fires for the matching PID.
    func prepareSession(sessionId: String, targetPid: Int32) async throws -> Bool
}

public final class ImeClient: ImeCaller, Sendable {
    private let connection: VoxConnection
    private let timeout: TimeInterval?

    public init(connection: VoxConnection, timeout: TimeInterval? = 30.0) {
        self.connection = connection
        self.timeout = timeout
    }

    public func setMarkedText(sessionId: String, text: String) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        payloadBytes += encodeString(text)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: ime_method_schemas[0x2d335085427db481]!, schemaRegistry: ime_schema_registry)
        let response = try await connection.call(methodId: 0x2d335085427db481, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func commitText(sessionId: String, text: String) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        payloadBytes += encodeString(text)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: ime_method_schemas[0x5716af924e8ded0f]!, schemaRegistry: ime_schema_registry)
        let response = try await connection.call(methodId: 0x5716af924e8ded0f, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func stopDictating(sessionId: String) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: ime_method_schemas[0x68519c24d46321b4]!, schemaRegistry: ime_schema_registry)
        let response = try await connection.call(methodId: 0x68519c24d46321b4, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }

    public func prepareSession(sessionId: String, targetPid: Int32) async throws -> Bool {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeString(sessionId)
        payloadBytes += encodeI32(targetPid)
        let payload = Data(payloadBytes)
        let schemaInfo = ClientSchemaInfo(methodInfo: ime_method_schemas[0x237826434890468a]!, schemaRegistry: ime_schema_registry)
        let response = try await connection.call(methodId: 0x237826434890468a, metadata: [], payload: payload, retry: .volatile, timeout: timeout, prepareRetry: nil, finalizeChannels: nil, schemaInfo: schemaInfo)
        var cursor = 0
        let _cursor_resultDisc = try decodeVarint(from: response, offset: &cursor)
        switch _cursor_resultDisc {
        case 0:
            let result = try decodeBool(from: response, offset: &cursor)
            return result
        case 1:
            let _cursor_errorCode = try decodeU8(from: response, offset: &cursor)
            switch _cursor_errorCode {
            case 0:
                throw VoxError.decodeError("unexpected user error for infallible method")
            case 1:
                throw VoxError.unknownMethod
            case 2:
                throw VoxError.decodeError("invalid payload")
            case 3:
                throw VoxError.cancelled
            case 4:
                throw VoxError.indeterminate
            default:
                throw VoxError.decodeError("invalid VoxError discriminant: \(_cursor_errorCode)")
            }
        default:
            throw VoxError.decodeError("invalid Result discriminant: \(_cursor_resultDisc)")
        }
    }
}

// MARK: - Ime Server

///  Methods the IME exposes — app calls into IME.
public protocol ImeHandler: Sendable {
    ///  App sends marked text to the IME for display.
    func setMarkedText(sessionId: String, text: String) async throws -> Bool
    ///  App tells IME to commit text and end the session.
    func commitText(sessionId: String, text: String) async throws -> Bool
    ///  App tells IME to stop dictating (cancel/abort).
    func stopDictating(sessionId: String) async throws -> Bool
    ///  App pushes a prepared session to the IME. IME should claim it
    ///  when activateServer fires for the matching PID.
    func prepareSession(sessionId: String, targetPid: Int32) async throws -> Bool
}

public final class ImeChannelingDispatcher: ServiceDispatcher {
    private let handler: ImeHandler
    private let schemaRegistry: [UInt64: Schema]
    private let methodSchemas: [UInt64: MethodSchemaInfo]

    public init(handler: ImeHandler, schemaRegistry: [UInt64: Schema] = ime_schema_registry, methodSchemas: [UInt64: MethodSchemaInfo] = ime_method_schemas) {
        self.handler = handler
        self.schemaRegistry = schemaRegistry
        self.methodSchemas = methodSchemas
    }

    public func dispatch(methodId: UInt64, payload: [UInt8], requestId: UInt64, registry: ChannelRegistry, schemaSendTracker _: SchemaSendTracker, taskTx: @escaping @Sendable (TaskMessage) -> Void) async {
        let payload = Data(payload)
        let taskSender: TaskSender = taskTx
        switch methodId {
        case 0x2d335085427db481:
            await dispatch_setMarkedText(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x5716af924e8ded0f:
            await dispatch_commitText(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x68519c24d46321b4:
            await dispatch_stopDictating(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        case 0x237826434890468a:
            await dispatch_prepareSession(methodId: methodId, requestId: requestId, payload: payload, registry: registry, taskSender: taskSender)
        default:
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
        }
    }

    public func retryPolicy(methodId: UInt64) -> RetryPolicy {
        switch methodId {
        case 0x2d335085427db481:
            return .volatile
        case 0x5716af924e8ded0f:
            return .volatile
        case 0x68519c24d46321b4:
            return .volatile
        case 0x237826434890468a:
            return .volatile
        default:
            return .volatile
        }
    }

    /// Pre-register Rx channel IDs from request payloads.
    /// Call this synchronously before spawning the dispatch task to avoid
    /// race conditions where Data arrives before channels are registered.
    public func preregister(methodId: UInt64, payload: [UInt8], registry: ChannelRegistry) async {
        let payload = Data(payload)
        switch methodId {
        default:
            break
        }
    }

    private func dispatch_setMarkedText(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            let text = try decodeString(from: payload, offset: &cursor)
            do {
                let result = try await handler.setMarkedText(sessionId: sessionId, text: text)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_commitText(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            let text = try decodeString(from: payload, offset: &cursor)
            do {
                let result = try await handler.commitText(sessionId: sessionId, text: text)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_stopDictating(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            do {
                let result = try await handler.stopDictating(sessionId: sessionId)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

    private func dispatch_prepareSession(methodId: UInt64, requestId: UInt64, payload: Data, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) async {
        guard let methodInfo = methodSchemas[methodId] else {
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
            return
        }
        let responseSchemaPayload = methodInfo.buildPayload(direction: .response, registry: schemaRegistry)
        do {
            var cursor = 0
            let sessionId = try decodeString(from: payload, offset: &cursor)
            let targetPid = try decodeI32(from: payload, offset: &cursor)
            do {
                let result = try await handler.prepareSession(sessionId: sessionId, targetPid: targetPid)
                taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBool($0) }), methodId: methodId, schemaPayload: responseSchemaPayload))
            } catch {
                taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
            }
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError(), methodId: methodId, schemaPayload: responseSchemaPayload))
        }
    }

}

// MARK: - Ime Schemas

public let ime_schemas: [String: MethodBindingSchema] = [
    "setMarkedText": MethodBindingSchema(args: [.string, .string]),
    "commitText": MethodBindingSchema(args: [.string, .string]),
    "stopDictating": MethodBindingSchema(args: [.string]),
    "prepareSession": MethodBindingSchema(args: [.string, .i32]),
]

/// Global schema registry containing all schemas for this service.
nonisolated(unsafe) public let ime_schema_registry: [UInt64: Schema] = [
    0x178367a87f66fb46: Schema(id: 0x178367a87f66fb46, typeParams: [], kind: .primitive(.bool)),
    0x281c5be4f2ee63b4: Schema(id: 0x281c5be4f2ee63b4, typeParams: [], kind: .primitive(.u32)),
    0x361f4536eee9f991: Schema(id: 0x361f4536eee9f991, typeParams: [], kind: .primitive(.i32)),
    0x42046de663beeef0: Schema(id: 0x42046de663beeef0, typeParams: ["T", "E"], kind: .enum(name: "Result", variants: [VariantSchema(name: "Ok", index: 0, payload: .newtype(typeRef: .var(name: "T"))), VariantSchema(name: "Err", index: 1, payload: .newtype(typeRef: .var(name: "E")))])),
    0x4cf4b2aeb98a1939: Schema(id: 0x4cf4b2aeb98a1939, typeParams: ["E"], kind: .enum(name: "VoxError", variants: [VariantSchema(name: "User", index: 0, payload: .newtype(typeRef: .var(name: "E"))), VariantSchema(name: "UnknownMethod", index: 1, payload: .unit), VariantSchema(name: "InvalidPayload", index: 2, payload: .newtype(typeRef: .concrete(0x6d7dce914ee150e8))), VariantSchema(name: "Cancelled", index: 3, payload: .unit), VariantSchema(name: "ConnectionClosed", index: 4, payload: .unit), VariantSchema(name: "SessionShutdown", index: 5, payload: .unit), VariantSchema(name: "SendFailed", index: 6, payload: .unit), VariantSchema(name: "Indeterminate", index: 7, payload: .unit)])),
    0x5db70a394660f3e6: Schema(id: 0x5db70a394660f3e6, typeParams: [], kind: .primitive(.never)),
    0x6847ab90feda71c1: Schema(id: 0x6847ab90feda71c1, typeParams: ["T0"], kind: .tuple(elements: [.var(name: "T0")])),
    0x6d7dce914ee150e8: Schema(id: 0x6d7dce914ee150e8, typeParams: [], kind: .primitive(.string)),
    0xba0496aa8cee7a4c: Schema(id: 0xba0496aa8cee7a4c, typeParams: ["T0", "T1"], kind: .tuple(elements: [.var(name: "T0"), .var(name: "T1")])),
]

/// Per-method schema information for wire protocol.
nonisolated(unsafe) public let ime_method_schemas: [UInt64: MethodSchemaInfo] = [
    0x2d335085427db481: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x5716af924e8ded0f: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x68519c24d46321b4: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x6847ab90feda71c1],
        argsRoot: .generic(0x6847ab90feda71c1, args: [.concrete(0x6d7dce914ee150e8)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
    0x237826434890468a: MethodSchemaInfo(
        argsSchemaIds: [0x6d7dce914ee150e8, 0x361f4536eee9f991, 0xba0496aa8cee7a4c],
        argsRoot: .generic(0xba0496aa8cee7a4c, args: [.concrete(0x6d7dce914ee150e8), .concrete(0x361f4536eee9f991)]),
        responseSchemaIds: [0x178367a87f66fb46, 0x281c5be4f2ee63b4, 0x42046de663beeef0, 0x5db70a394660f3e6, 0x6d7dce914ee150e8, 0x4cf4b2aeb98a1939],
        responseRoot: .generic(0x42046de663beeef0, args: [.concrete(0x178367a87f66fb46), .generic(0x4cf4b2aeb98a1939, args: [.concrete(0x5db70a394660f3e6)])])
    ),
]

public struct ImeSerializers: BindingSerializers {
    public init() {}

    public func txSerializer(for schema: BindingSchema) -> @Sendable (Any) -> [UInt8] {
        switch schema {
        case .bool: return { encodeBool($0 as! Bool) }
        case .u8: return { encodeU8($0 as! UInt8) }
        case .i8: return { encodeI8($0 as! Int8) }
        case .u16: return { encodeU16($0 as! UInt16) }
        case .i16: return { encodeI16($0 as! Int16) }
        case .u32: return { encodeU32($0 as! UInt32) }
        case .i32: return { encodeI32($0 as! Int32) }
        case .u64: return { encodeVarint($0 as! UInt64) }
        case .i64: return { encodeI64($0 as! Int64) }
        case .f32: return { encodeF32($0 as! Float) }
        case .f64: return { encodeF64($0 as! Double) }
        case .string: return { encodeString($0 as! String) }
        case .bytes: return { [UInt8]($0 as! Data) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not serialized directly")
        default: fatalError("Unsupported schema for Tx serialization: \(schema)")
        }
    }

    public func rxDeserializer(for schema: BindingSchema) -> @Sendable ([UInt8]) throws -> Any {
        switch schema {
        case .bool: return { var o = 0; return try decodeBool(from: Data($0), offset: &o) }
        case .u8: return { var o = 0; return try decodeU8(from: Data($0), offset: &o) }
        case .i8: return { var o = 0; return try decodeI8(from: Data($0), offset: &o) }
        case .u16: return { var o = 0; return try decodeU16(from: Data($0), offset: &o) }
        case .i16: return { var o = 0; return try decodeI16(from: Data($0), offset: &o) }
        case .u32: return { var o = 0; return try decodeU32(from: Data($0), offset: &o) }
        case .i32: return { var o = 0; return try decodeI32(from: Data($0), offset: &o) }
        case .u64: return { var o = 0; return try decodeVarint(from: Data($0), offset: &o) }
        case .i64: return { var o = 0; return try decodeI64(from: Data($0), offset: &o) }
        case .f32: return { var o = 0; return try decodeF32(from: Data($0), offset: &o) }
        case .f64: return { var o = 0; return try decodeF64(from: Data($0), offset: &o) }
        case .string: return { var o = 0; return try decodeString(from: Data($0), offset: &o) }
        case .bytes: return { Data($0) }
        case .tx(_, _), .rx(_, _): fatalError("Channel schemas are not deserialized directly")
        default: fatalError("Unsupported schema for Rx deserialization: \(schema)")
        }
    }
}

